### ISSUE TITLE
Soll-Kriterium 32: Rechnung druckfertig...

### ISSUE THREAD

**Issue by pheim1** [marlonschlosshauer/blob-frontend#23]
Laut Pflichtenheft soll auch eine Funktion für das erstellen einer Rechnung vorhanden sein. 
Habe ich es letztes mal falsch verstanden, da nur die rede von dem Lieferschein war?

**Comment by marlonschlosshauer** [comment]
Es muss auch eine Rechnung erstellbar sein.

**Comment by pheim1** [comment]
> Es muss auch eine Rechnung erstellbar sein.

Alles klar, dann wird mir @sfuerder die Buttons an den richtigen stelle erstellen und ich werde dann den Rest machen...

**Comment by marlonschlosshauer** [comment]
Wir können dann die gleiche Logik für die Buttons wie in #24 verwenden.
