### ISSUE TITLE
Soll-Kriterium 31: Erstellung des Lieferscheins

### ISSUE THREAD

**Issue by pheim1** [marlonschlosshauer/blob-frontend#24]
Laut Pflichtenheft ist das erstellen des Lieferscheins im **"In-Bearbeitung- und Archivieren-Tab"** möglich, wurde aber von @sfuerder im **Versand-Tab** implementiert, müssen wir das Pflichtenheft oder unser Programm anpassen?

**Comment by marlonschlosshauer** [comment]
@sfuerder Würde es weniger Arbeit machen das einfach bei allen Tabs (Nicht Bezahlt, In-Bearbeitung) etc. einzufügen ?

So wie es steht muss es zumindest bei In-Bearbeitung, Versand- und Archivieren zur Verfügung stehen.

**Comment by sfuerderer** [comment]
Ist beides einfach zu lösen. Deshalb werde ich es so machen, wie es im Pflichtenheft steht

**Comment by marlonschlosshauer** [comment]
Sehr gut, dann machen wir es so wie es im Pflichtenheft steht.
