### ISSUE TITLE
Bestellungen: Ändern des Status

### ISSUE THREAD

**Issue by pheim1** [marlonschlosshauer/blob-frontend#30]
Bei dem ändern des Status kommt eine Fehlermeldung, siehe Bilder. Es wird verschoben, aber es erscheint fälschlicherweise eine Fehlermeldung.

![image](https://user-images.githubusercontent.com/58334704/84770446-daafb880-afd7-11ea-9095-2cce56aa3754.png)

![image](https://user-images.githubusercontent.com/58334704/84770466-e4392080-afd7-11ea-81cc-1454eca1723e.png)

![image](https://user-images.githubusercontent.com/58334704/84770487-ef8c4c00-afd7-11ea-90b4-3687f06ca6ac.png)

**Comment by sfuerderer** [comment]
Ich bekomme da einen 404 Zurück. Angeblich findet er das Bestellte Produkt mit der ID nicht. Beim Get ist das Produkt aber mit in der Bestellung drin.
@pheim1  Eine Idee woran das liegen kann? Muss ich was anderes senden?

**Comment by pheim1** [comment]
Womöglich das Problem, dass ihr die Product.Id sendet, anstelle der OrderedProduct.Id? Oder andersrum 😅

**Comment by pheim1** [comment]
Auf die schnelle würde mir nur einfallen, die Fehlermeldung zu unterdrücken, da es ja funktioniert...

**Comment by sfuerderer** [comment]
Es wird genau das gesendet, was ich bekomme. Bis auf, dass halt der Status geändert wurde.

**Comment by sfuerderer** [comment]
> Auf die schnelle würde mir nur einfallen, die Fehlermeldung zu unterdrücken, da es ja funktioniert...

Kann ich machen

**Comment by pheim1** [comment]
Es ist halt ein elendiges Thema mit den Id´s...
Im Prinzip hast du recht, du sendest natürlich das was du bekommst... Vllt müssen wir beim testen genau hinschauen und womöglich ein Issue beim Backend machen, falls uns was auffällt.

**Comment by sfuerderer** [comment]
Okay. Wie kann ich Fehlermeldungen filtern? Kann ich auf den error code zugreifen?

**Comment by pheim1** [comment]
Ja das muss möglich sein, wenn du im error closure des subscribs den error parameter mal anschaust.

**Comment by pheim1** [comment]
error.status; gibt glaube ich den Status-Code

**Comment by sfuerderer** [comment]
So wie es aussieht funktioniert das ändern tatsächlich gar nicht. Bei einem Reload ist die Bestellung wieder im alten tab.

**Comment by sfuerderer** [comment]
> error.status; gibt glaube ich den Status-Code

damit kann ich nicht darauf zugreifen

**Comment by pheim1** [comment]
Ok, ich werde mal darüber nachdenken, wie wir es von backend Seiten Lösen können, da ich vermute, das dort der Fehler liegt.

Ich close diesen hier mal, Änderungen an dem frontend sind bis jetzt nicht Nötig.

**Comment by pheim1** [comment]
Wurde durch Issue 58 von dem Backend gefixed.
