### ISSUE TITLE
Produkt: Suche ist case sensitive

### ISSUE THREAD

**Issue by pheim1** [marlonschlosshauer/blob-frontend#31]
Wenn man was sucht, sollte es egal sein ob es groß oder klein geschrieben ist... ist auch einfach zu lösen -> string.toLowerCase( ) == otherString.toLowerCase( )

Nicht Kritisch aber nicht, dass es bei dem Testen als Fehler angesehen wird...

![image](https://user-images.githubusercontent.com/58334704/84801251-3b062080-afff-11ea-9dd0-be722b520faa.png)

![image](https://user-images.githubusercontent.com/58334704/84801295-46594c00-afff-11ea-946c-4c59f0407a31.png)

![image](https://user-images.githubusercontent.com/58334704/84801322-507b4a80-afff-11ea-9e72-caadecb444cd.png)

**Comment by BenjaminKuerten** [comment]
Wir morgen behoben
