### ISSUE TITLE
Order: Bearbeitung einer Bestellung setzt den Status auf 1

### ISSUE THREAD

**Issue by pheim1** [marlonschlosshauer/blob-frontend#32]
Bei der Bearbeitung der Bestellung nr42, welche im Status in-bearbeitung war, wurde bei dem req an das Backend der Status mit der ID 1 mitgeschickt... Somit wird bei einer Änderung der Status immer auf 1 gesetzt...

```json
[
  {
    "id": 42,
    "createdAt": null,
    "customer": {
      "id": 29,
      "firstname": null,
      "lastname": null,
      "address": null,
      "createdAt": null
    },
    "orderedProducts": [
      {
        "id": 18,
        "name": null,
        "price": 0,
        "sku": null,
        "quantity": 2
      },
      {
        "id": 1,
        "name": "Yokohama Advan Sport V103",
        "price": 0,
        "sku": null,
        "quantity": 10
      },
      {
        "id": 2,
        "name": "DUNLOP SPORT CLASSIC",
        "price": 0,
        "sku": null,
        "quantity": 3
      }
    ],
    "state": {
      "id": 1,
      "value": "Nicht Bezahlt"
    }
  }
]

```

**Comment by sfuerderer** [comment]
Dachte das soll so sein. Wenn ich eine Bestellung ändere und Produkte hinzufüge ist sie ja theoretisch nicht bezahlt. 
Ist es richtig, wenn sie den Status behält?

**Comment by pheim1** [comment]
> Dachte das soll so sein. Wenn ich eine Bestellung ändere und Produkte hinzufüge ist sie ja theoretisch nicht bezahlt.
> Ist es richtig, wenn sie den Status behält?

Ok so macht es dann natürlich sinn, haben wir diese Funktionalität irgendwo dokumentiert? Weil für mich war es in erste Linie ein Bug, ohne das zu wissen 😅

@marlonschlosshauer Was denkst du?

**Comment by marlonschlosshauer** [comment]
Ich hätte gesagt die Bestellung sollte den Status beibehalten, aber das Verhalten ist kein Problem.
