### ISSUE TITLE
Product: Produkte werden 1:1 kopiert

### ISSUE THREAD

**Issue by WilliamAkaWill** [marlonschlosshauer/blob-frontend#36]
Ich habe das erste Produkt kopiert und wollte ohne etwas zu ändern das Produkt speichern.
Das Produkt wurde gespeichert und war in der Produktliste einsehbar.
Laut Spezifikation 5 heißt es, dass bei Name und SKU eine zahl hinzugefügt werden damit es einzigartig bleibt, dies ist nicht geschehen und wir haben jetzt den fall geschaffen das wir 2 mal die gleiche SKU haben was Sie nicht mehr einzigartig macht.

**Comment by BenjaminKuerten** [comment]
War das nicht gewollt?
Beispiel von @marlonschlosshauer, ich habe 2 Nagellacke einen in rot und einen in blau, dann ist der Name und die SKU doch trotz gleich oder?

**Comment by BenjaminKuerten** [comment]
"5.4 Name und SKU wird Zahl hinzugefügt (das einzigartig bleibt)"

SKU wird eine Zahl hinzugefügt macht zudem absolut kein Sinn

**Comment by pheim1** [comment]
Also aus meiner Erfahrung (nicht so viel im E-Commerce) kenne ich es, das man die SKU nutzt um die unterschiedlichen Produkten zu unterscheiden, also einProdukt -> zwei Farben... -> zwei SKU´s.

**Comment by BenjaminKuerten** [comment]
Eine SKU ist eine Artikelnummer, diese werden zentral von einer Organisation vergeben, sonst würde Barcodes ja nicht funktionieren

**Comment by marlonschlosshauer** [comment]
Die SKU sollte geändert werden. Das zweite Produkt sollte z.B. MSC4 -> MSC5
Am besten machen wir noch eine Zahl am Ende vom Namen hin, so das es bei Service auch funktioniert. 

Gut das du das gefunden hast.

**Comment by BenjaminKuerten** [comment]
So ist eine SKU aufgebaut 
2-Stellen Ländercode + 5-Stellen Herstellercode + 5-Stellen Artikelnummer + Prüfziffer

**Comment by pheim1** [comment]
> Eine SKU ist eine Artikelnummer, diese werden zentral von einer Organisation vergeben, sonst würde Barcodes ja nicht funktionieren

SKU hat doch im ersten Moment nichts mit Barcodes zu tun. Der Barcode würde im Endeffekt eh nur anhand der SKU generiert, die SKU kann die Firma auch lokal für sich manuell generieren.

**Comment by pheim1** [comment]
Wichtig ist nur das es nicht die gleiche SKU hat, wenn es eine andere Eigenschaft hat => Kopie mit Modifikationen. In RealUseCase wird der Bearbeiter eh die SKU anpassen, aber wir müssen feststellen, dass es nicht die SKU der vorherigen wiederverwendet

**Comment by BenjaminKuerten** [comment]
Der Barcode stellt die SKU grafisch da.
Ich ändere das ab, dass eine Zahl hinzugefügt wird.
Wobei das in meinen Augen funktional keinen Sinn macht,
da eine Artikelnummer von der EAN vergeben wird, sonst ist es eine Herstellernummer und keine SKU/Artikelnummer.

**Comment by BenjaminKuerten** [comment]
Fixed
