### ISSUE TITLE
Product: Bei gleicher SKU erfolgt keine Fehlermeldung 

### ISSUE THREAD

**Issue by WilliamAkaWill** [marlonschlosshauer/blob-frontend#38]
Beim Erstellen eines neuen Produktes, kann man eine Vorhandene SKU.
Es Erfolgt keine Fehlermeldung und das Produkt wird normal gespeichert.
Dies Verstößt gegen die Spezifikation 3.

**Comment by BenjaminKuerten** [comment]
Implizit zu #36

**Comment by BenjaminKuerten** [comment]
Fixed
