### ISSUE TITLE
Login: Groß und Kleinschreibung wird Ignoriert

### ISSUE THREAD

**Issue by WilliamAkaWill** [marlonschlosshauer/blob-frontend#39]
Wenn ich als benutzter in der Datenbank Hinterlegt bin, ergibt sich der Benutzername aus den Buchstaben vom Vornamen und Nachnamen.
Wenn ich mich jetzt als William Mendat registriere ist mein Benutzername WMendat. 
Großes W, Großes M und danach alles klein. Das Funktioniert auch.
Nun habe ich gemerkt, das ich mich aber auch mit wmendat als auch mit WMENDAT einloggen kann.
ist das so gewohlt?

**Comment by pheim1** [comment]
Ist so gewollt, macht wenig Sinn es case sensitiv zu machen, da ja die Kombination von Buchstaben eindeutig ist unabhängig von deren groß/klein Schreibung
