### ISSUE TITLE
Order: Seltsames verhalten beim Produkt "Felgenreiniger stark 500ml" hinzufügen/verändern

### ISSUE THREAD

**Issue by WilliamAkaWill** [marlonschlosshauer/blob-frontend#40]
Während ich ein bisschen das hinzufügen und verändern von Produkten in Bestellung getestet habe, ist mir aufgefallen, dass ich die Anzahl des Produktes Felgenreiniger stark 500ml nicht verändern konnte obwohl man noch genug bestand hatte. Es kommt eine Fehlermeldung wenn ich versuche diese Produkt zu verändern. Gleiches Verhalten passiert bei den Produkten Felgenreiniger und Reifen Sommer. Also ich kann das Produkt der Bestellung hinzufügen aber im nahenein die anzahl nicht ändern obwohl man noch genug bestand hat.

**Comment by pheim1** [comment]
Wurde im Backend gefixed: commit 9db240ee688852837875f972c8df0f1bf7481962

**Comment by marlonschlosshauer** [comment]
Bei Bestellung 54 und 59 kann der "Felgenreiniger stark 500ml" [nicht hinzugefügt werden](https://giant.gfycat.com/AshamedDefensiveAdmiralbutterfly.webm) (trotz vorhandenem Bestand). 
Bei Bestellungen 61 hat es aber funktionieren. 

Möglicherweise ein Problem weil die 50er Bestellungen mit einer alten Version erstellt wurde ?

**Comment by pheim1** [comment]
Ich habe gerade festgestellt, dass in Bestellung 54 das Geistesprodukt die ID 48 hat, genau wie der Felgenreiniger. Ich vermute es hat was mit dem Backend zu tun, ich werde es jetzt kontrollieren.

**Comment by pheim1** [comment]
Fixed im backend mit **`commit 3755c2a`**
