### ISSUE TITLE
Product: Mehrfach Auswahl des gleichen Standortes 

### ISSUE THREAD

**Issue by marlonschlosshauer** [marlonschlosshauer/blob-frontend#44]
Ich hab bei einem Produkt zwei mal den gleichen Standort ausgewählt. 
Es kam eine Fehlermeldung ([Der ausgewählte Standort wird bereits benutzt](https://user-images.githubusercontent.com/24259317/85065415-66c70900-b1ad-11ea-8fc4-62e0bc6f53ad.png)) hat aber trotzdem den Standort ausgewählt.  

Sieht so aus als müsste die Auswahl nach dem der Fehler erkannt wurde, zurückgesetzt werden.

**Comment by BenjaminKuerten** [comment]
@marlonschlosshauer Speichern des Produktes ist nicht möglich, beim Speichern wird ein Fehler ausgegeben. Möchte keine User-Eingabe hart überschreiben. Optischer "Fehler" - Ist Entscheidungssache was davon schöner ist.

**Comment by marlonschlosshauer** [comment]
Also eine Lösung sollte auf jeden Fall her. "Filiale 1" sollte nicht zweimal auswählbar sein, vor allem wenn dadurch das Speichern nicht mehr korrekt funktioniert.  

Das Überschreiben wäre etwas zu viel weil es andere Daten noch löschen könnte, oder ? 
@pheim1 Kann man die Liste von verfügbaren Standorten beim Dropdown Filtern ? So das schon ausgewählte Locations nicht mehr auftauchen ?

**Comment by pheim1** [comment]
> @pheim1 Kann man die Liste von verfügbaren Standorten beim Dropdown Filtern ? So das schon ausgewählte Locations nicht mehr auftauchen ?

Durch die `new Set(...)` werden Duplikate gelöscht
`listOfLocations = [...new Set(listOfLocations)]`

Falls man zwei listen hat, kann man mit der .filter(...)-Funktion die welche in Liste 1 vorkommen aus der Liste 2 filter. Hier eine schnelle vllt. unoptimierte Lösung, da zwei schleifen:
`listOfLocations = listOfLocations.filter(loc => !selectedLocations.findIndex(x => x != loc))`

**Comment by marlonschlosshauer** [comment]
> `listOfLocations = listOfLocations.filter(loc => !selectedLocations.findIndex(x => x != loc))`

Sehr funktional. Gefällt mir. Ich glaube man sollte aber noch eine Location Liste als Backup behalten, falls man wieder eine Location löscht. 

@BenjaminKuerten Was meinst du ?

**Comment by pheim1** [comment]
> (...) Ich glaube man sollte aber noch eine Location Liste als Backup behalten, falls man wieder eine Location löscht.

Ja gut erkannt, ist wichtig. NGZorro bestrebt glaube ich den Ansatz, die Rohdaten als z.B.` listOfLocations` zu benennen und die welche angezeigt werden als, `listOfLocationsDisplay`

**Comment by BenjaminKuerten** [comment]
Die Umsetzung ist nicht das Problem, ich kann auch direkt die Spalte wieder entfernen.
"vor allem wenn dadurch das Speichern nicht mehr korrekt funktioniert"- Es funktioniert, du bekommt nur ein Fehler angezeigt, dass du deine Standorte überprüfen sollst.

**Comment by BenjaminKuerten** [comment]
Mein Problem ist gerade nur, dass ich den Fehler nicht finde. Wir reden über einen Bug, der nicht existiert. Du kannst unter keinen Umständen 2 mal die gleiche Location bei einem Produkt haben.

**Comment by pheim1** [comment]
![image](https://user-images.githubusercontent.com/58334704/85124357-1641c100-b22a-11ea-905b-555683a6dac4.png)

So darf das nicht dastehen, auch wenn es so nicht an das backend geschickt wird.

**Comment by BenjaminKuerten** [comment]
Direkt bei Auswählen: https://prnt.sc/t2nmg0
Beim Speichern: https://prnt.sc/t2nmq8

Es ist nicht möglich 2 mal den selben Standort zu haben.

**Comment by BenjaminKuerten** [comment]
Du kannst so nicht auf Speichern drücken

**Comment by BenjaminKuerten** [comment]
Dann lösche ich es halt direkt wieder raus, ist eine Zeile Code. 
Entspricht nur gegen alle Usecase Regeln das direkt wieder zu löschen.
Der User soll das Programm bedienen und nicht das Programm den User.
Aber ok. #Closed Update kommt

**Comment by pheim1** [comment]
> Der User soll das Programm bedienen und nicht das Programm den User.

**So lange die Funktion steht, was sie tut, bin ich eigentlich ok damit wie es ist, da es nur ein UX update wäre und das können wir uns nicht leisten.** 

Ich persönlich hätte dem User nicht die Möglichkeit gegeben, die Location nochmals auszuwählen wenn sie schon ausgewählt wurde. 

Da ein Programm den User unterstützen soll und ihn nicht nur auf Fehler hinweisen soll, die Idee eines Programmes ist das unterstützen, und verbessern eines Arbeitsablaufes was auch heißt, das es schneller geht...

**Comment by marlonschlosshauer** [comment]
> Es ist nicht möglich 2 mal den selben Standort zu haben.
> Du kannst so nicht auf Speichern drücken

Habe es [gerade probiert](https://giant.gfycat.com/LargeAccomplishedBluejay.webm) (v1.2 von 2 Tagen) und konnte beides machen. Das war die Live version. Hast du es Lokal getestet oder reden wir möglicherweise aneinander vorbei ? 

Ich bekomme die Fehlermeldung, aber die zweite Location wird trotzdem ausgewählt. Der Speichern Button ist noch aktiv, nur wenn man ihn drückt kommt man eben in den Limbo. 

> Der User soll das Programm bedienen und nicht das Programm den User.

Wir haben bisher diese Philosophie verfolgt, aber ich finde es ist Zeit das wir uns dem User anpassen. Ich glaube das wird uns als Fehler angeschrieben werden.

**Comment by BenjaminKuerten** [comment]
Gerade kam ein Update auf Master, die das zweimal Auswählen nicht mehr möglich macht.
Unterschiedliche Designansätze, aber gleiche Funktion.
