### ISSUE TITLE
Löschen von Standort mit Produkten

### ISSUE THREAD

**Issue by BenjaminKuerten** [marlonschlosshauer/blob-frontend#49]
Wirft ein Fehler in der Console (und Fehlermeldung nicht passend).

Fehlermeldung: https://prnt.sc/t2ov4p
Error: https://prnt.sc/t2owox

**Comment by pheim1** [comment]
Bitte auch ein Screenshot von dem Response des Requests -> Network-Tab

**Comment by BenjaminKuerten** [comment]
"Es darf kein Produkt mehr an diesem Standort vorhanden sein bevor es gelöscht werden kann"

**Comment by pheim1** [comment]
![guck](https://user-images.githubusercontent.com/58334704/85129253-14303000-b233-11ea-873d-ec48d9907a5d.gif)

**Comment by pheim1** [comment]
Bitte auch hinzuschreiben: 
Was sollte passieren - Was ist passiert...

**Comment by BenjaminKuerten** [comment]
Erwartung: Beim löschen eines Standortes mit Produkten soll ein Fehler erscheinen, dass dieser nicht gelöscht werden kann. Lade-Animation soll wieder beendet werden nach Klick auf "ok".

Ergebnis: Beim Klick auf löschen bei einem Standort mit Produkten erscheint eine Fehlermeldung *1 und ein Error *2 in der Konsole. Die Lade-Animation endet nie.

*1 Beim Löschen des Standortes ist ein Fehler aufgetreten, bitte benachrichtigen Sie den Administrator.

*2 400 (Bad Request) - "Es darf kein Produkt mehr an diesem Standort vorhanden sein bevor es gelöscht werden kann"

**Comment by pheim1** [comment]
Also dann ist ja die Implementierung des Backends richtig oder?

**Comment by BenjaminKuerten** [comment]
Ja und Nein, Frage der Implementierung.

Das Frontend kann schwer herausfinden ob ein Standort noch Produkte hat, wäre aber möglich - Durchgehen alle Produkte und check auf Location-ID.

Das Backend könnte aber auch statt dem Error einen leeres "Data" Feld schicken, oder wie bei Produkt "NO SKU DEFINED".

**Comment by pheim1** [comment]
Das backend sendet doch die Fehlermeldung das reicht, an die kommst du ran. Im Subscribe beim error-Branch

**Comment by BenjaminKuerten** [comment]
Habe mir noch nie die Implementation angeguckt.
Code stammt von @marlonschlosshauer und @sfuerder

**Comment by BenjaminKuerten** [comment]
Ich gucke es mir mal an
