### ISSUE TITLE
404 bei direktem Zugriff auf Subdomain

### ISSUE THREAD

**Issue by marlonschlosshauer** [marlonschlosshauer/blob-frontend#51]
Wenn ich auf [/product](http://176.31.26.11/product) direkt zugreife bekomme ich ein 404. 
Ich hätte erwartet das es mir die Seite gibt. Scheint so als wäre die Produktseite nur verfügbar wenn man erst die Homepage besucht.

Ich gehe mal davon aus das daran liegt das Angular die Seite auf dem Client normalerweise für sich routet, anstatt wirklich einen GET Request an die Adresse zu schicken.

Ich bin zuerst darauf aufmerksam geworden als ich die Seite neu laden wollte. @pheim1 Hast du dafür einen Fix im Kopf ? Ist nicht wirklich ein Problem, aber wenn du was weißt und Zeit hast können wir das gerne noch einbauen. 

<img width="562" alt="Screenshot 2020-06-19 at 17 27 07" src="https://user-images.githubusercontent.com/24259317/85150354-b7dd0880-b252-11ea-9cde-7f4438c1a39d.png">

**Comment by pheim1** [comment]
Es liegt, wie du erahnt hast daran, dass wenn du die index.html (mit dem Pfad / ) herunterlädst, die angular app laden tust. Angular tut alle module und components in js files laden und diese werden dann von der index.html verwaltet. Der Server hat also nur auf dem Pfad / eine Datei, die index.html.

Ein fix wäre mit einer .htaccess möglich, wo alle req auf den Pfad / umgeleitet werden, und dann der zusätzlich Pfad dran gehängt wird.

**Comment by pheim1** [comment]
Wir laden ja die index.html + alle JS files (components, module usw.) lokal auf unseren Browser Cache und davon navigieren wir ja dann innerhalb der app. Der Pfad wird nur manipuliert und gibt den eintrug, dass man bei einem neuen Pfad eine neue Seite vom Server lädt. In Wirklichkeit wird aber lokal einfach ein neues component im Browser angezeigt.
