### ISSUE TITLE
UX: Produkt hinzufügen alignment

### ISSUE THREAD

**Issue by pheim1** [marlonschlosshauer/blob-frontend#52]
Im Kunden- & Bestellungsdashboard sind die Buttons links Zentriert, beim Produkt aber rechts zentriert wirkt nicht so Konsistenz.

![image](https://user-images.githubusercontent.com/58334704/85155726-65531a80-b259-11ea-8c32-30b9136973ea.png)

![image](https://user-images.githubusercontent.com/58334704/85155749-713edc80-b259-11ea-969e-4b4a62453814.png)

**Comment by BenjaminKuerten** [comment]
Ich zentriere Ihn in Produkt rechts
