### ISSUE TITLE
Less styles zusammen fassen

### ISSUE THREAD

**Issue by sfuerderer** [marlonschlosshauer/blob-frontend#6]
Ich habe das Dashboard vom Kunden jetzt auch schon gemacht, und da sich das Design dem vom Produkt ähnelt habe ich in der less Datei vom Kunden Dashboard jetzt den gleichen css code wie Benny im Produkt Dashboard.
Wäre es da nicht sinnvoller diesen less code zusammen zufassen und in die oberste less Datei zu schreiben?

**Comment by pheim1** [comment]
Wenn euch sowas auffällt, könnt ihr es in die `style.less` reinschreiben, die ist Global.

**Comment by marlonschlosshauer** [comment]
Gute Idee. Wenn #7 durchgeht könnte man dafür nen Commit machen.

**Comment by BenjaminKuerten** [comment]
Finde ich auch gut, da die Seiten sehr ähnlich sind.

**Comment by sfuerderer** [comment]
Habe es mit dem commit e03f689a5a779f42a4068280f94ceeb3b2926d35 zusammengefügt
