### ISSUE TITLE
Order: Felgenreiniger 500ml Stark wird als Michelin Sport Cup 6 angezeigt

### ISSUE THREAD

**Issue by marlonschlosshauer** [marlonschlosshauer/blob-frontend#63]
Ich wollte eine Bestellung mit dem Felgenreiniger 500ml Stark machen. [Diese wird dann aber in der Bestellung als "Michelin Pilot Sport Cup 6" angezeigt](https://giant.gfycat.com/FocusedEnlightenedCommabutterfly.webm).
Ich kann den Felgenreiniger dann auch nicht der Bestellung hinzufügen. 

<img width="475" alt="Screenshot 2020-06-21 at 14 34 01" src="https://user-images.githubusercontent.com/24259317/85224690-55a81300-b3cc-11ea-94bc-eaf282ea875b.png">

Der Bestand des Felgenreiniger wird beim erstellen auch dekrementiert, [aber darauf folgende Änderungen verringern den Bestand des Michelin Sport Cup 6.](https://giant.gfycat.com/CrazyIncomparableGander.webm) 

Geht hier um Bestellung 73 und 75. 
Consol ist leer. Getestet auf Live. 

Ich erinnere mich daran das wir da ein Problem hatten, etwas mit den 50er Bestellungen.
Kann es sein das das noch ein Problem mit dem Felgenreiniger 500ml Stark ist ?

**Comment by marlonschlosshauer** [comment]
Wenn ich eine Bestellung mit dem Pilot Sport Cup 6 mache, die verändere, wird der Bestand korrekt bei dem Pilot Sport Cup 6 abgezogen.

**Comment by marlonschlosshauer** [comment]
Ich habe "Reifen Sommer" Bestand an 3 Standorten gegeben und dann eine Bestellung mit ihm gemacht. [Der wird als Yokoahama Advan Sport V107 abgespeichert](https://giant.gfycat.com/GlaringVastGoshawk.webm).

Wie auch oben wird der Bestand beim erstellen korrekt bei "Reifen Sommer" dekrementiert, aber beim Bearbeiten nicht mehr.

**Comment by pheim1** [comment]
Ok, das wird dann ein Bug mit den ID´s sein, muss an dem OrderController liegen.

**Comment by pheim1** [comment]
Wurde mit commit 85462f7 im backend gefixed. Durch den fix hatte sich ein zweiten Bug (Folgefehler) eingeschlichen, den habe ich während des Tests auch gefixed.
