### ISSUE TITLE
Locations in den Mockups

### ISSUE THREAD

**Issue by pheim1** [marlonschlosshauer/blob-frontend#8]
Ich bin die Mockups mal durchgegangen und konnte bei Bestellungen keine Auswahl der Location finden, wie wird das dann realisiert? Hat da jemand eine Idee?

**Comment by BenjaminKuerten** [comment]
Darüber haben wir mal diskutiert, wir wollten es erstmal stupide machen und einfach dort wo der meiste Bestand vorhanden ist. Wobei ich da gerade eine sinnvollere und auch nicht viel schwierigere Idee hätte. In Deutschland fangen Postleitzahlen mit 1-9 an und wir könnten einfach immer die nähst am Kunden nehmen.

Beispiel 1:
**Geschäftsstandorte**:
11111 Berlin
79108 Freiburg
**Kunde** 
34054 XXXX
Also wird Berlin genommen

Beispiel 2:
**Geschäftsstandorte**:
11111 Berlin
79108 Freiburg
**Kunde** 
94248 XXXX
Also wird Freiburg genommen

Wäre eine for mit einem if oder?

**Comment by pheim1** [comment]
@BenjaminKuerten Wäre zumindest eine Lösung, laut ERM haben wir ja nur bei den Produkten und Kunden eine direkte Relation zu den Locations.

Aus Backend-Sicht würde ich dann einfach von dem Frontend eine LocationId erwarten oder sollte diese Logic dann das Frontend realisieren?

**Comment by BenjaminKuerten** [comment]
Beispiel 2:
Und sollte in Freiburg nicht genug Bestand da sein dann:
1. Nimm einen anderen Standort
2. den Rest aus Freiburg + noch offene von Berlin

Ist eine Definition, würde dann einen anderen Standort wählen der Einfachheit halber.

**Comment by marlonschlosshauer** [comment]
> Aus Backend-Sicht würde ich dann einfach von dem Frontend eine LocationId erwarten oder sollte diese Logic dann das Frontend realisieren?

Ich stelle es mir so vor das das Frontend beim erstellen der Bestellung extra Request an den ProductController sendet, in denen der Bestand der Produkten verändert wurde. 
  
Gehe also davon aus das das REST Backend hier nur als Schnittstelle zur DB dient.

**Comment by pheim1** [comment]
Also wir machen es denk so wie in Issue 6 vom Backend beschrieben, das Frontend muss sich dann nicht darum kümmern den bestand zu vermindern. Für die Einfachheit des Projektes wäre ich für den einfachen Algorithmus: Bestand dort verringern wo am meisten vorhanden sind, sonst zum nächst meisten weiter gehen. Falls aber nicht genügend vorhanden sind, wird das Backend eine Fehler zurückwerfen!
