### ISSUE TITLE
Fehlermeldung Title Service

### ISSUE THREAD

**Issue by sfuerderer** [marlonschlosshauer/blob-frontend#9]
<img width="1358" alt="Bildschirmfoto 2020-05-25 um 14 56 30" src="https://user-images.githubusercontent.com/37979892/82814729-fb349900-9e97-11ea-92aa-23476e967f21.png">

Ich bekomme in meiner Konsole diese Fehlermeldung. So wie es aussieht liegt es an dem TitleService. Ich weiß jetzt nicht woran es liegt. Vllt kennt ja jemand die Lösung bzw woran es liegt

**Comment by pheim1** [comment]
Versuch mal den Titel innerhalb der `ngAfterViewInit`-Methode, anstelle der `ngInit` Methode.

Für `ngAfterViewInit` musst du das `AfterViewInit`-Interface bei deinem component implementieren.

**Comment by sfuerderer** [comment]
<img width="1358" alt="Bildschirmfoto 2020-05-25 um 15 12 38" src="https://user-images.githubusercontent.com/37979892/82815812-346e0880-9e9a-11ea-9eaa-0ab903250585.png">

Das Problem besteht immer noch. Vllt hat es damit was zu tun. Jedesmal wenn ich in der Navigation einen Link anklicke kommt eine Fehlermeldung dazu

**Comment by pheim1** [comment]
Laut Stackoverflow kann es auch folgende Methode sein: `ngAfterContentInit`,

https://stackoverflow.com/a/45341146

**Comment by sfuerderer** [comment]
Bekomme immer noch den Fehler. 
Aber funktionieren tut bisher trotzdem alles. Es ist nur die Fehlermeldung in der Konsole.

**Comment by pheim1** [comment]
Wie in dem Beitrag zu lesen ist, hat es was mit der ChangeDetection von angular zu tun.

Versuch mal den Titel im constructor zu ändern. Alternativ kann auch ein timeout der changedetection etwas Zeit geben, wobei das etwas Trickprogrammierung ist ...

Ich hatten den Fehler schonmal ein einem Projekt, aber ich muss ehrlich gestehen, dass ich die Lösung vergessen habe 😂

**Comment by sfuerderer** [comment]
Okay. Wenn man den Titel im Konstrukt ändert funktioniert es. 👍🏻
